version: "3.8"

services:
  vote:
    build: ./vote
    ports:
      - "5000:3000"
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "5001:4000"
    depends_on:
      - db

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  redis:
    image: redis:6-alpine

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes

